### ISSUE TITLE
Better volume translation?

### ISSUE THREAD

**Issue by dannye** [mtolly/pokemid#16]
It doesn't seem like volume changes are properly reflected when going between formats.

**Comment by mtolly** [comment]
Do you mean using MIDI note velocity? Correct, currently it just uses the `notetype` text events to encode volume and ignores MIDI velocity. I'd change it if you have a suggestion for how it should work; the volume parameter (2nd arg to `notetype`) appears to range from 0 to 15, so should each of those get about 1/16 of the 1 to 127 MIDI velocity range?

**Comment by dannye** [comment]
I think it would be easier to work with if it translated midi velocity into `notetype` volume.
But yeah, I would do something like:
volume = velocity * 15/127
And  I would probably round up no matter what so that any positive velocity guarantees a volume of at least 1.

Otherwise, how do I add text events like `notetype` in an editor like FL Studio?

**Comment by dannye** [comment]
It's worth noting that a volume of 0 is never used except for in dungeon1.asm:
https://github.com/iimarckus/pokered/blob/master/audio/music/dungeon1.asm#L232
But that's because the note that is being played immediately fades in.

A volume of 0 technically works, but creates a weird clicking sound every time a silent note is played, so it isn't useful really.

**Comment by mtolly** [comment]
I've released a new version 0.8 with this implemented. Let me know if it works as you expect!
